### PR TITLE
Fix SPM tests layout

### PR DESCRIPTION
**Pull request by apparition47**
What's in this pull request?
============================

Move all tests into a "Tests" subfolder to satisfy SPM (updated your `.xcodeproj` too).

Why merge this pull request?
============================

Fix for #318

What's worth discussing about this pull request?
================================================

[My other PR](https://github.com/typelift/Swiftx/pull/59) for your Swiftx dependency must also be merged for this fix to be complete. Also, when I was following your [SwiftCheck SPM format](https://github.com/typelift/SwiftCheck/tree/master/Tests), I noticed you have a `LinuxMain.swift` -- not sure if that's needed for this.

What downsides are there to merging this pull request?
======================================================

n/a

### CODE REVIEW

**Comment by CodaFi** [comment]
Can you run `git submodule foreach git pull origin master` to bring in the latest Swiftx changes too please?  I'm going to put out a new version soon, so please bump up the package version range to accommodate that

**Comment by apparition47** [comment]
Done -- I think I did it 7c28c51

**Comment by CodaFi** [comment]
Ah, looks like one of the tests must be updated with a bit of new syntax for some of the methods in `SwiftCheck`.  I have it set up so it should appear as fix-it suggestions if you simply build the testing target for `Swiftz`.

**Comment by apparition47** [comment]
My bad, I should've ran through that before I did the PR. Thanks.

**Comment by CodaFi** [comment]
Looks good.  Last thing to do is bump [this version requirement](https://github.com/typelift/Swiftz/blob/master/Package.swift#L10) up a skosh to match the new version of Swiftx.

**Comment by apparition47** [comment]
`0.5.1..0.5.1` is okay?

**Comment by CodaFi** [comment]
Yep

**Comment by CodaFi** [comment]
⛵️

**Comment by CodaFi** [comment]
New version incoming.

**Pull request merged**
