### PR TITLE
Improve Num

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by vendethiel** [comment]
Seems weird to have an issue to rename Num to (possibly) NumericType, then introduce "Ratio", no? (even if "Rational" is introduced the same commit)

**Comment by CodaFi** [comment]
The difference is Ratio is a fully expanded noun.  What other name could there be for a structure of 2 Integral values related by the division operation?

**Comment by CodaFi** [comment]
Tying this to #230

**Comment by CodaFi** [comment]
I'm going to cap this pull request here and stop making changes.  The Fractional hierarchy will come in a later pull request.

Ready for Review.

**Comment by pthariensflame** [comment]
This looks fine to me.  :+1:

**Comment by CodaFi** [comment]
:boat:

**Pull request merged**
