### PR TITLE
Test JSON with SwiftCheck

### PR DESCRIPTION
**Pull request by CodaFi**
Per the discussion in #264

### CODE REVIEW

**Comment by mpurland** [comment]
@CodaFi What about negative tests for JSONValue.decode?

**Comment by CodaFi** [comment]
I need to think more about how to generate JSON.  But it's not a big deal right now seeing as all we're doing is shunting whatever value foundation gives us back into the JSONValue struct. To test that would be to test NSJSONSerialization, not anything Swiftz-related.

**Comment by CodaFi** [comment]
I was thinking of creating an ArbitraryJSONValue struct that simultaneously constructs a JSON string and a parallel ideal JSONValue and testing against that.

**Comment by mpurland** [comment]
That could work. I wonder if that could be used in conjunction with generators for each JSONValue type array, object, string, and all types of numbers.

**Comment by CodaFi** [comment]
But I wonder what that amount of engineering would actually accomplish in terms of testability.  So I've got JSON, I've got a model "built" from it.  Great.  What invariants hold about the structure?  None I can think of.  

I took a look, and Aeson uses a set of big JSON files along with its test suite to stress-test and have some real-world use cases.  That seems more productive in the long run.

**Comment by mpurland** [comment]
I think so too. I was trying to accomplish that on a small scale (at least for numbers) in JSONSpec. If more tests were added (like in Aeson) I think it would accomplish enough test coverage for the JSON decoder & encoder.

Reference: https://github.com/bos/aeson/tree/master/benchmarks/json-data

**Comment by CodaFi** [comment]
I'll try this again later.

**Pull request closed without merging**
