### PR TITLE
Comonads; Good for something

### LINKED ISSUE #119: Comonad, what's it good for?
We don't have any instances of Comonad in the framework.  I'm starting to think it would be better served in a new framework in the same vein as Category-Extras where we can better flesh out these ideas.  If not, it would be trivial to write a Comonad instance for at least Box<T>.  What do you think?

### PR DESCRIPTION
**Pull request by CodaFi**
Fixes #119 and #20

Now hearing arguments as to whether Copointed is a good idea.

### CODE REVIEW

**Comment by CodaFi** [comment]
Ugh.  Soooo many weird linker bugs still reside in Swiftc.

**Comment by pthariensflame** [comment]
@CodaFi :(

**Comment by CodaFi** [comment]
@pthariensflame  Ready for Review

**Comment by pthariensflame** [comment]
:+1:

**Comment by pthariensflame** [comment]
In the absence of objections, merging.

**Pull request merged**
