### PR TITLE
Add a podspec file

### LINKED ISSUE #97: Cocoapod Spec?
Cocoapod distribution will reduce the barrier for some of us to try out swiftz.  Is this in swiftz future?

### PR DESCRIPTION
**Pull request by ikesyo**
Fixes #97.

### CODE REVIEW

**Comment by pthariensflame** [comment]
@CodaFi Do you want to include @maxcan, @tLewisII, and/or @mxswd as authors, in addition to you and me?

**Comment by CodaFi** [comment]
When and if they request it, sure.  But I haven't seen activity from a lot of them in a while (for some of them with good reason).  For now just you and me seems prudent.

**Comment by pthariensflame** [comment]
I'm fine with that.  Merging!

**Comment by CodaFi** [comment]
Also, thank you so much for this change!  Is there a way we can alter Travis to run a build on the CP spec too?

**Pull request merged**
