### PR TITLE
Make builds more consistent

### PR DESCRIPTION
**Pull request by mpurland**

### CODE REVIEW

**Comment by mpurland** [comment]
If this works and is acceptable we can probably use this across the rest of the TypeLift projects

**Comment by CodaFi** [comment]
Agreed.  I suck at writing these kinds of things, and I wrote them all :sweat_smile:

**Comment by mpurland** [comment]
Took me awhile last night to figure out why the iOS tests were stalling in Tyro on Travis...what a headache. Hopefully this works...

**Comment by CodaFi** [comment]
Give this one the old rebase and it'll be good.

**Comment by CodaFi** [comment]
Give this one the old rebase and it'll be good.

**Comment by mpurland** [comment]
:boat:

**Pull request merged**
