### PR TITLE
Uniformize 'match' as a computed properties for String. Fix issue #291

### PR DESCRIPTION
**Pull request by gcornut**

### CODE REVIEW

**Comment by mpurland** [comment]
:+1:

**Comment by mpurland** [comment]
:boat:

**Comment by mpurland** [comment]
@gcornut Thanks for the PR!

**Comment by CodaFi** [comment]
@gcornut Yeah, thanks!  :sparkles:

**Comment by gcornut** [comment]
You're welcome 👍🏻. It wasn't much

**Pull request merged**
