### PR TITLE
Removed JSON from Swiftz

### PR DESCRIPTION
**Pull request by mpurland**

### CODE REVIEW

**Comment by CodaFi** [comment]
This is... quite aggressive, but we're right in the range where we should probably release a new dot version anyhow.

:+1:

Since this is so big: @pthariensflame do you see anything?

**Comment by mpurland** [comment]
Since this will be a breaking chance, should the next version be 0.4.0?

**Comment by CodaFi** [comment]
Yep

**Comment by CodaFi** [comment]
Definitely need to get around to finalizing the API over in Tyro before this lands.  I'm drawing up something now.

**Comment by pthariensflame** [comment]
This looks okay to me, although it's midnight where I am, so take any of my recommendations accordingly.  :stuck_out_tongue_winking_eye:

**Comment by mpurland** [comment]
@CodaFi Any red flags so far?
 
@pthariensflame If you have a chance, let me know what you think of Tyro.

**Comment by CodaFi** [comment]
Always good to see progress like this

screen shot 2015-11-21 at 3 42 48 pm

:boat:

**Comment by mpurland** [comment]
Now it's time to wait and see how many issues come in.

**Pull request merged**
