### PR TITLE
Better Together

### PR DESCRIPTION
**Pull request by CodaFi**
We're splitting up, kids, but it's for the best.

### CODE REVIEW

**Comment by CodaFi** [comment]
image

Ready for review.

**Comment by pthariensflame** [comment]
Well, *this'll* take a while.  :P

**Comment by CodaFi** [comment]
Lucky for you the changes are entirely cosmetic.  Just want you to make sure I didn't Bork the transition (like how this didn't work for the past zillion commits because git's "you renamed this file" implementation is case-insensitive-I blame HFS).

**Comment by pthariensflame** [comment]
Ok.  Looks good to me, but I'm trusting Travis more than myself on something like this.  :P

**Comment by CodaFi** [comment]
That's the last uncaught change I can see.  This will go through when Travis gives me the green light.

**Comment by CodaFi** [comment]
:boat:

**Pull request merged**
