### PR TITLE
State Monad

### PR DESCRIPTION
**Pull request by CodaFi**
Adds the plain (and currently utterly useless) State monad.

Swift 1.1 is not a fan of the Monad instance.

### CODE REVIEW

**Comment by pthariensflame** [comment]
Can we add conversions between `State<S, A>` and `IxState<S,S,A>`?

If only Swift supported generic `typealias`es…

**Comment by CodaFi** [comment]
Mm, yeah.  I'll open an issue as a reminder (because every other language with typedefs and generics doesn't seem to have a problem with this).

**Comment by pthariensflame** [comment]
To be fair, if you're not careful, type-level lambdas (which is what generic type aliases amount to) can break the decidability of type-checking.  Still. *something* should be able to be done…

**Comment by CodaFi** [comment]
OK.  Ready for review.

**Comment by pthariensflame** [comment]
:+1:

**Comment by CodaFi** [comment]
:boat:

**Pull request merged**
