### PR TITLE
in comment line 11:  lilsts -> lists   (typo?)

### PR DESCRIPTION
**Pull request by mareklug**

### CODE REVIEW

**Comment by CodaFi** [comment]
Why did you close this?

**Comment by mareklug** [comment]
I'm sorry, it was a mistake on my part. I am only learning how to use git. Who exactly closes this?

**Comment by CodaFi** [comment]
You already closed it, but I have the power to close and reopen these things to, which is what I'd like to do.  If you don't have any more changes to make, I'm going to reopen and merge this.  It's a great change to have.

**Comment by mareklug** [comment]
Thank you. No more changes at this point.  I hope to pick up all the nuances soon. ;)

Marek

**Comment by CodaFi** [comment]
Alright then.  

:boat:

**Pull request merged**
