### PR TITLE
Modernize The README

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
Right now, it feels very bare.  If anyone has anything they want to add, I'm all ears.

**Comment by mpurland** [comment]
The JSON example could use some updating now that the JSON example has changed. I would either remove the User.create function or convert it to a explicit curried function.

**Comment by CodaFi** [comment]
@mpurland Done.  See anything else?

**Comment by mpurland** [comment]
@CodaFi I think this is good for now, but we should add documentation for using <?? and enums. This could even be broken out into a separate JSON serialization documentation README. What do you think?

**Pull request merged**
