### PR TITLE
Improve String Extension

### LINKED ISSUE #193: Combinators for String
If String wishes to act like an opaque ordered container of Characters, it seems more than appropriate to treat it like one and extend it the same courtesy we do for Lists.

### PR DESCRIPTION
**Pull request by CodaFi**
... by treating it like List<Character>.

Fixes #193.

### CODE REVIEW

**Comment by CodaFi** [comment]
Character needs a CoArbitrary instance in SwiftCheck before those function specs can be uncommented.

**Comment by CodaFi** [comment]
OK.  The tests, like, actually run now.]

@pthariensflame Ready for review.

**Comment by pthariensflame** [comment]
:+1:

**Comment by CodaFi** [comment]
Eyy,

:boat:

**Pull request merged**
